name: Test

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install Node packages
              run: pnpm install

            - name: Check code format
              run: pnpm run check-format

            - name: Run tests
              run: pnpm run test
